version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000,https://videtopia.net,https://www.videtopia.net
      - MAX_FILE_SIZE=104857600
      - UPLOAD_DIR=./uploads
      - OUTPUT_DIR=./outputs
      - CLEANUP_INTERVAL=300000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - videtopia-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - videtopia-network

networks:
  videtopia-network:
    driver: bridge

volumes:
  uploads:
  outputs:
